name: Pipeline
 
on:
  push:
    branches: [main]
 
jobs:
  test_soma:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
 
    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v5
 
      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
 
      - name: Executar Teste de Soma
        run: node soma.js
 


  test_sub:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
 
    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v5
 
      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
 
      - name: Executar Teste de Subtração
        run: node sub.js
 
  test_div:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
 
    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v5
 
      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
 
      - name: Executar Teste de Divisão
        run: node div.js

  test_elevar:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v5

      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Executar Teste de Elevar Número
        run: node elevar.js

  test_raiz:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    
    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v5

      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'

      - name: Executar Teste de Raiz Quadrada
        run: node raiz.js
 

  deploy:
    needs: [test_soma, test_sub, test_div, test_raiz, test_elevar]
    runs-on: ubuntu-latest
 
    steps:
      - name: Deploy
        run: echo "Deploy realizado"